name: Build with GCC Cross x86_64-elf

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and Run Docker Container
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
          tags: quantamos:latest
        id: docker_build

      - name: Run Docker Container
        run: |
          docker run --rm -v ${{ github.workspace }}:/root/env/ quantamos:latest
