name: Build Quantum New

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install necessary packages
      run: |
        sudo apt update
        sudo apt install -y git g++ make libncurses-dev unzip bc bzip2 libelf-dev libssl-dev extlinux wget

    - name: Download and extract Buildroot
      run: |
        wget https://buildroot.org/downloads/buildroot-2024.02.4.tar.gz
        tar -xzf buildroot-2024.02.4.tar.gz

    - name: Change directory to Buildroot
      run: cd buildroot-2024.02.4

    - name: Run make menuconfig
      run: |
        cd buildroot-2024.02.4
        make menuconfig

    - name: Build Buildroot
      run: |
        cd buildroot-2024.02.4
        make -j$(nproc)
